# Generated by Django 4.2.30 on 2026-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Libellé de la dépense')),
                ('categorie', models.CharField(choices=[('loyer', 'Loyer'), ('electricite', 'Électricité / Eau'), ('transport', 'Transport / Logistique'), ('salaire', 'Salaires'), ('marketing', 'Publicité'), ('divers', 'Divers / Autres')], default='divers', max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'depenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
