# Generated by Django 4.2.30 on 2026-04-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('produits', '0001_initial'),
        ('tailles', '0001_initial'),
        ('couleurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='couleurs.couleur')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres.genre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='produits.produit')),
                ('taille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailles.taille')),
            ],
            options={
                'db_table': 'produitVariations',
                'unique_together': {('produit', 'taille', 'couleur')},
            },
        ),
    ]
