# Generated by Django 4.2.30 on 2026-05-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('produits', '0001_initial'),
        ('tailles', '0001_initial'),
        ('couleurs', '0001_initial'),
        ('produitVariations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produitvariation',
            unique_together={('produit', 'taille', 'genre', 'couleur')},
        ),
    ]
