# Generated by Django 4.2.30 on 2026-05-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produitVariations', '0002_alter_produitvariation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.CharField(blank=True, max_length=150, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_attente', 'En attente'), ('annule', 'Annulé')], default='recu', max_length=20)),
            ],
            options={
                'db_table': 'achats',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.achat')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produitVariations.produitvariation')),
            ],
            options={
                'db_table': 'ligne_achats',
            },
        ),
    ]
