# Generated by Django 4.2.30 on 2026-05-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produitVariations', '0002_alter_produitvariation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('methode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('momo', 'Mobile Money (Momo)')], default='ESPECES', max_length=20)),
                ('status', models.CharField(choices=[('valide', 'Validée'), ('annule', 'Annulée')], default='valide', max_length=20)),
            ],
            options={
                'db_table': 'ventes',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produitVariations.produitvariation')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'db_table': 'ligne_ventes',
            },
        ),
    ]
