# Generated by Django 4.2.30 on 2026-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('assistant', 'Assistant')], default='assistant', max_length=20),
        ),
    ]
